steps:
# Pull a previous image, if exists to use cache for faster builds
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME} || exit 0

# Build the new image
- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME}',
      '--cache-from', 'gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME}',
      '.'
    ]

# Push the image to Google Cloud Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME}']

# Tag the image for GCR and Cloud Build
images: 
- 'gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME}'

timeout: 900s