steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME} || exit 0

# Build the image with the mounted volume
- name: 'gcr.io/cloud-builders/docker'
  args: 
    [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME}-${SHORT_SHA}',
      '--cache-from', 'gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME}',
      '.'
    ]

# Push the image to gcr.io
images: 
- 'gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME}-${SHORT_SHA}'
- 'gcr.io/$PROJECT_ID/${REPO_NAME}:${BRANCH_NAME}'

# Global build timeout
timeout: "900s"
