steps:
- name: 'postgres:11'
  env:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
- name: 'docker/compose:1.24.0'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
timeout: '900s'