steps:
- name: gcr.io/cloud-builders/docker
  args: ['run', '-d', '--name=postgres', '--network=cloudbuild', 'postgres']
- name: 'postgres'
  env:
    - POSTGRES_PASSWORD=odoo
    - POSTGRES_USER=odoo
  args: ['psql', '--host=postgres', '--user=odoo', '--command', 'SELECT * FROM INFORMATION_SCHEMA.Tables']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']
- name: 'docker/compose:1.24.0'
  args: ['up', '-d']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
timeout: '900s'