steps:
- name: 'docker/compose:1.24.0'
  args: ['up']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'dockerdoo:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']