version: '3.4'

x-odoo:
  &default-odoo
  tty: true
  build: .
  image: odoo:${ODOO_VERSION}
  ports: ['8069:8069', '8072:8072']
  volumes:
    # Named volumes
    - odoo-data:/var/lib/odoo
    - odoo-testlogs:/var/log/odoo
    # Odoo source Host path
    - ./extra_addons:/mnt/extra-addons:ro
    # Odoo configuration Host path
    - ./config:/etc/odoo:ro
  depends_on:
    - postgres
  networks:
    - odoonet

networks:
  odoonet:

volumes:
  db_data: {driver: local}
  odoo-data: {driver: local}
  odoo-testlogs: {driver: local}
  psql: {driver: local}

services:

# ------------------------

  wdb:
    image: xoes/wdb-server
    ports: ['1984:1984']
    networks:
      - odoonet

# ------------------------

  postgres:
    image: postgres:10
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
        # TODO: this variables shouldn't be hardcoded
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    networks:
      odoonet:
        aliases:
          - db

# ------------------------

  odoo:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh']
    # TODO: add a variable to allow a dynamic ADDONS_PATH
    command: ['odoo']
    depends_on: ['postgres']

# ========================

  dev:
    << : *default-odoo
    entrypoint: ['/entrypoint.sh']
    command: ['odoo', '--dev', 'wdb,reload,qweb,werkzeug,xml']
    depends_on: ['postgres', 'wdb']

# ------------------------

  tests:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh']
    # TODO: logfile shouldn't be hardcoded
    command: ['odoo', '--dev', 'wdb,qweb,werkzeug,xml', '--test-enable', '--stop-after-init', '--logfile', '/var/log/odoo/odoo-server.log']

# ------------------------

  shell:
    << : *default-odoo
    depends_on: ['postgres', 'wdb']
    entrypoint: ['/entrypoint.sh']
    command: ['odoo', 'shell']
