version: '3.4'

networks:
  default:
    external:
      name: cloudbuild
  odoonet:

volumes:
  db_data:
  odoo-data:
  odoo-testlogs:
  psql:

services:

  postgres:
    image: postgres:${PSQL_VERSION:-11}
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-odoo}
      - POSTGRES_USER=${POSTGRES_USER:-odoo}
    networks:
      odoonet:
        aliases:
          - db
      - default

# ------------------------

  odoo:
    tty: true
    image: iterativodo/dockerdoo:latest
    environment:
      # Libraries version
      WKHTMLTOX_VERSION: ${WKHTMLTOX_VERSION}
      WKHTMLTOPDF_CHECKSUM: ${WKHTMLTOPDF_CHECKSUM}
      NODE_VERSION: ${NODE_VERSION}
      BOOTSTRAP_VERSION: ${BOOTSTRAP_VERSION}

    ports: ['8069:8069', '8072:8072']

    volumes:
      # Host paths (addons & conf)
      - ./src/odoo/ee:/opt/odoo/addons/ee:ro
      - ./custom:/mnt/extra-addons
      - ./config:/etc/odoo:ro
      # Named volumes
      - odoo-data:/var/lib/odoo/data
      - odoo-testlogs:/var/lib/odoo/logs

    depends_on:
      - postgres
    networks:
      - default
      - odoonet
